<center>
<h4>Diplomatura AACSyA 2018 - FaMAF - UNC</h4>
<h3>Aprendizaje Supervisado</h3>
<hr>
<h4>Por David Gonzalez <leonardo.david.gonzalez@gmail.com> y Facundo Díaz Cobos <facundo.diaz.cobos@gmail.com></h4>
</center>
<br/>

# Aprendizaje Supervisado: Laboratorio 2 - Iteracion 1


Movies Reviews Sentiment Analysis

    Trabajo final de laboratorio de la materia Aprendizaje Supervisado (Matías Marenchino, Franco M. Luque)
    Diplomatura en Ciencias de Datos, Aprendizaje Automático y sus Aplicaciones http://diplodatos.famaf.unc.edu.ar/


In [67]:
from util import load_datasets_unlabeled_test
from util import save_results
# Obtenemos los datos en arreglos
train, dev, test = load_datasets_unlabeled_test()
X_train, y_train = train
X_dev, y_dev = dev

## Bag-of-words

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()
vect.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [45]:
x = vect.transform([X_train[0]])
x


<1x16112 sparse matrix of type '<class 'numpy.int64'>'
	with 53 stored elements in Compressed Sparse Row format>

In [46]:
features = vect.get_feature_names()

In [47]:
vect = CountVectorizer(min_df=2)
vect.fit(X_train)
x = vect.transform(X_train[:1])
x

<1x7767 sparse matrix of type '<class 'numpy.int64'>'
	with 53 stored elements in Compressed Sparse Row format>

## Min counts

In [48]:
vect = CountVectorizer(min_df=2)
vect.fit(X_train)
x = vect.transform(X_train[:1])
x

<1x7767 sparse matrix of type '<class 'numpy.int64'>'
	with 53 stored elements in Compressed Sparse Row format>

In [49]:
features = vect.get_feature_names()
len(features)

7767

In [50]:
positive_words = [
    'good',
    'best',
    'excellent',
    'awesome',
    'love',
    'happy'
]
negative_words = [
    'bad',
    'worst',
    'sad',
    'unhappy'
    'weak',
    'low',
    'damaged',
    'boring',
    'waste',
    'bored',
    'garbage',
    'ridiculous',
    'bore',
    'wrong',
    'disappointed',
    'horrendous',
    'awful',
]
vocabulary = positive_words + negative_words

In [10]:
vect = CountVectorizer(vocabulary=vocabulary, binary=True)
vect.fit(X_train)


<1x9 sparse matrix of type '<class 'numpy.int64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline

from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC, SVC
from sklearn.ensemble import RandomForestClassifier

clfs = [
    KNeighborsClassifier(),
    MultinomialNB(),
    DecisionTreeClassifier(random_state=0),
    LogisticRegression(random_state=0),
    LinearSVC(random_state=0),
    SVC(random_state=0),
    RandomForestClassifier(random_state=0),
]


In [51]:
for clf in clfs:
    print(str(clf.__class__))
    pipeline = Pipeline([
        ('vect', vect),
        ('clf', clf),
    ])
    pipeline.fit(X_train, y_train)
    
    print_short_eval(pipeline, X_train, y_train)
    print_short_eval(pipeline, X_dev, y_dev)

<class 'sklearn.neighbors.classification.KNeighborsClassifier'>
accuracy	0.78	macro f1	0.78
accuracy	0.67	macro f1	0.67
<class 'sklearn.naive_bayes.MultinomialNB'>
accuracy	0.96	macro f1	0.96
accuracy	0.85	macro f1	0.85
<class 'sklearn.tree.tree.DecisionTreeClassifier'>
accuracy	1.00	macro f1	1.00
accuracy	0.71	macro f1	0.71
<class 'sklearn.linear_model.logistic.LogisticRegression'>
accuracy	1.00	macro f1	1.00
accuracy	0.84	macro f1	0.84
<class 'sklearn.svm.classes.LinearSVC'>
accuracy	1.00	macro f1	1.00
accuracy	0.78	macro f1	0.77
<class 'sklearn.svm.classes.SVC'>
accuracy	0.64	macro f1	0.62
accuracy	0.67	macro f1	0.66
<class 'sklearn.ensemble.forest.RandomForestClassifier'>
accuracy	0.99	macro f1	0.99
accuracy	0.72	macro f1	0.71


## Nos decidimos por naive_bayes


In [63]:
clf = MultinomialNB(alpha=3)
## PROBAR HIPERPARAMETROS
pipeline = Pipeline([('vect', vect),('clf', clf),])
pipeline.fit(X_train, y_train)
print_short_eval(pipeline, X_train, y_train)
print_short_eval(pipeline, X_dev, y_dev)
print_short_eval(pipeline)



accuracy	0.95	macro f1	0.95
accuracy	0.89	macro f1	0.89


["The music track of this version is made up of various romantic symphonies and overtures . At first the effect seems quite pleasing . Then you realize that no attempt has been made to match the mood of the visuals with the music , so you end up with things like a light-hearted scherzo during the first appearance of the vampire , or Dvorak 's `` New World '' symphony over the arrival of the vampire in Bremen . The music track eventually becomes an unbearable distraction and the only thing to do is to hit the mute button .",
 'I gave this to my 4 year and 2 year old grandchildren . They absolutely loved it . We watched it everyday for about 5 days . They got a real kick out of their father joining in and knowing the words and the story . It is definitely a family movie .',
 "i was n't expecting much from this dvd ... .but what i got back from it was beyond my expectations.The backstage footage was great . It makes you realize that they are n't heartless demons . They are actually drunke

# Probando el clasificador:
Probemos nuestro clasificador inicial

In [55]:
pipeline.predict(['this movie is truly good'])

array([1])

In [56]:
pipeline.predict(['this movie is truly bad'])

array([0])

In [75]:
predictions = pipeline.predict(test)

In [76]:
predictions

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,

In [77]:

save_results("primer_intento", predictions )